version: "3.8"
services:

    redis:
        image: "redis"
        ports:
            - 6379:6379
        expose:
            - 6379
        restart:
            always

    node:
        build:
            context: ./nodejs
#        ports:
#          - 3000:8080
    
    nginx:
        build:
            context: ./nginx
        ports:
          - 80:80
        restart: always



    




