version: "3.8"
services:

    redis:
        image: "redis"
        ports:
            - 6379:6379
        # expose:
        #     - 6379
        restart:
            always

    go:
        build:
            context: ./golang
        # ports:
        #   - 9001:8080

    node:
        build:
            context: ./nodejs
        # ports:
        #    - 9002:8080


    nginx:
        build:
            context: ./nginx
        ports:
          - 8000:8000
        restart: always


    




    




